### ISSUE TITLE
Compatibilità Firefox

### ISSUE THREAD

**Issue by aborruso** [ondata/vaccinipertutti#14]
Su Firefox la renderizzazione dei campi non è buona

![](https://i.imgur.com/9G1wuBv.png)

**Comment by rosamarco** [comment]
Non sono sicuro che sia la soluzione migliore, ma può essere risolto aggiungendo 
```css
input[type=number] {
    width: 5ch;
}
```
in App.css
